/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) astrobee_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

static const casadi_real casadi_c0[3] = {6.5189048239895691e+00, 7.0077084793272606e+00, 6.1614294516327792e+00};
static const casadi_real casadi_c1[9] = {1.5340000000000001e-01, 0., 0., 0., 1.4269999999999999e-01, 0., 0., 0., 1.6230000000000000e-01};

/* astrobee_expl_vde_adj:(i0[12],i1[12],i2[6],i3[12])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, *w1=w+15, *w2=w+24, *w3=w+27, *w4=w+30, *w5=w+33, *w6=w+45, *w7=w+48, *w8=w+51, *w9=w+54, w10, w11, *w12=w+65, *w13=w+74, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, *w25=w+88, w26, *w27=w+95, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = zeros(3x3) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 
  [[6.5189, 00, 00], 
   [00, 7.00771, 00], 
   [00, 00, 6.16143]] */
  casadi_copy(casadi_c0, 3, w3);
  /* #4: @4 = @3' */
  casadi_trans(w3,casadi_s0, w4, casadi_s0, iw);
  /* #5: @5 = input[1][0] */
  casadi_copy(arg[1], 12, w5);
  /* #6: {@3, @6, @7, @8} = vertsplit(@5) */
  casadi_copy(w5, 3, w3);
  casadi_copy(w5+3, 3, w6);
  casadi_copy(w5+6, 3, w7);
  casadi_copy(w5+9, 3, w8);
  /* #7: @2 = mac(@4,@8,@2) */
  casadi_mtimes(w4, casadi_s0, w8, casadi_s1, w2, casadi_s1, w, 0);
  /* #8: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #9: @9 = 
  [[0.1534, 0, 0], 
   [0, 0.1427, 0], 
   [0, 0, 0.1623]] */
  casadi_copy(casadi_c1, 9, w9);
  /* #10: @5 = input[0][0] */
  casadi_copy(arg[0], 12, w5);
  /* #11: @8 = @5[9:12] */
  for (rr=w8, ss=w5+9; ss!=w5+12; ss+=1) *rr++ = *ss;
  /* #12: @4 = mac(@9,@8,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #13: @4 = @4' */
  /* #14: @1 = mac(@2,@4,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w4+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #15: @10 = @1[5] */
  for (rr=(&w10), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #16: @11 = 0 */
  w11 = 0.;
  /* #17: (@1[5] = @11) */
  for (rr=w1+5, ss=(&w11); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #18: @11 = @1[7] */
  for (rr=(&w11), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #19: @10 = (@10-@11) */
  w10 -= w11;
  /* #20: (@0[9] += @10) */
  for (rr=w0+9, ss=(&w10); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #21: @10 = 0 */
  w10 = 0.;
  /* #22: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #23: @10 = 0 */
  w10 = 0.;
  /* #24: @12 = @1; (@12[2] = @10) */
  casadi_copy(w1, 9, w12);
  for (rr=w12+2, ss=(&w10); rr!=w12+3; rr+=1) *rr = *ss++;
  /* #25: @10 = @12[6] */
  for (rr=(&w10), ss=w12+6; ss!=w12+7; ss+=1) *rr++ = *ss;
  /* #26: @11 = @1[2] */
  for (rr=(&w11), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #27: @10 = (@10-@11) */
  w10 -= w11;
  /* #28: (@0[10] += @10) */
  for (rr=w0+10, ss=(&w10); rr!=w0+11; rr+=1) *rr += *ss++;
  /* #29: @10 = 0 */
  w10 = 0.;
  /* #30: (@12[6] = @10) */
  for (rr=w12+6, ss=(&w10); rr!=w12+7; rr+=1) *rr = *ss++;
  /* #31: @10 = @12[1] */
  for (rr=(&w10), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #32: @11 = 0 */
  w11 = 0.;
  /* #33: (@12[1] = @11) */
  for (rr=w12+1, ss=(&w11); rr!=w12+2; rr+=1) *rr = *ss++;
  /* #34: @11 = @12[3] */
  for (rr=(&w11), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #35: @10 = (@10-@11) */
  w10 -= w11;
  /* #36: (@0[11] += @10) */
  for (rr=w0+11, ss=(&w10); rr!=w0+12; rr+=1) *rr += *ss++;
  /* #37: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #38: @12 = @9' */
  for (i=0, rr=w12, cs=w9; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #39: @13 = zeros(3x1) */
  casadi_clear(w13, 3);
  /* #40: @9 = zeros(3x3) */
  casadi_clear(w9, 9);
  /* #41: @10 = @5[11] */
  for (rr=(&w10), ss=w5+11; ss!=w5+12; ss+=1) *rr++ = *ss;
  /* #42: @11 = (-@10) */
  w11 = (- w10 );
  /* #43: (@9[3] = @11) */
  for (rr=w9+3, ss=(&w11); rr!=w9+4; rr+=1) *rr = *ss++;
  /* #44: (@9[1] = @10) */
  for (rr=w9+1, ss=(&w10); rr!=w9+2; rr+=1) *rr = *ss++;
  /* #45: @10 = @5[10] */
  for (rr=(&w10), ss=w5+10; ss!=w5+11; ss+=1) *rr++ = *ss;
  /* #46: (@9[6] = @10) */
  for (rr=w9+6, ss=(&w10); rr!=w9+7; rr+=1) *rr = *ss++;
  /* #47: @10 = (-@10) */
  w10 = (- w10 );
  /* #48: (@9[2] = @10) */
  for (rr=w9+2, ss=(&w10); rr!=w9+3; rr+=1) *rr = *ss++;
  /* #49: @10 = @5[9] */
  for (rr=(&w10), ss=w5+9; ss!=w5+10; ss+=1) *rr++ = *ss;
  /* #50: @11 = (-@10) */
  w11 = (- w10 );
  /* #51: (@9[7] = @11) */
  for (rr=w9+7, ss=(&w11); rr!=w9+8; rr+=1) *rr = *ss++;
  /* #52: (@9[5] = @10) */
  for (rr=w9+5, ss=(&w10); rr!=w9+6; rr+=1) *rr = *ss++;
  /* #53: @1 = @9' */
  for (i=0, rr=w1, cs=w9; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #54: @13 = mac(@1,@2,@13) */
  for (i=0, rr=w13; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #55: @4 = mac(@12,@13,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #56: @13 = zeros(3x1) */
  casadi_clear(w13, 3);
  /* #57: @12 = zeros(3x3) */
  casadi_clear(w12, 9);
  /* #58: @10 = 1 */
  w10 = 1.;
  /* #59: (@12[0] = @10) */
  for (rr=w12+0, ss=(&w10); rr!=w12+1; rr+=1) *rr = *ss++;
  /* #60: @10 = @5[6] */
  for (rr=(&w10), ss=w5+6; ss!=w5+7; ss+=1) *rr++ = *ss;
  /* #61: @11 = sin(@10) */
  w11 = sin( w10 );
  /* #62: @14 = @5[7] */
  for (rr=(&w14), ss=w5+7; ss!=w5+8; ss+=1) *rr++ = *ss;
  /* #63: @15 = tan(@14) */
  w15 = tan( w14 );
  /* #64: @16 = (@11*@15) */
  w16  = (w11*w15);
  /* #65: (@12[3] = @16) */
  for (rr=w12+3, ss=(&w16); rr!=w12+4; rr+=1) *rr = *ss++;
  /* #66: @16 = cos(@10) */
  w16 = cos( w10 );
  /* #67: @17 = tan(@14) */
  w17 = tan( w14 );
  /* #68: @18 = (@16*@17) */
  w18  = (w16*w17);
  /* #69: (@12[6] = @18) */
  for (rr=w12+6, ss=(&w18); rr!=w12+7; rr+=1) *rr = *ss++;
  /* #70: @18 = cos(@10) */
  w18 = cos( w10 );
  /* #71: (@12[4] = @18) */
  for (rr=w12+4, ss=(&w18); rr!=w12+5; rr+=1) *rr = *ss++;
  /* #72: @18 = sin(@10) */
  w18 = sin( w10 );
  /* #73: @18 = (-@18) */
  w18 = (- w18 );
  /* #74: (@12[7] = @18) */
  for (rr=w12+7, ss=(&w18); rr!=w12+8; rr+=1) *rr = *ss++;
  /* #75: @18 = sin(@10) */
  w18 = sin( w10 );
  /* #76: @19 = cos(@14) */
  w19 = cos( w14 );
  /* #77: @18 = (@18/@19) */
  w18 /= w19;
  /* #78: (@12[5] = @18) */
  for (rr=w12+5, ss=(&w18); rr!=w12+6; rr+=1) *rr = *ss++;
  /* #79: @20 = cos(@10) */
  w20 = cos( w10 );
  /* #80: @21 = cos(@14) */
  w21 = cos( w14 );
  /* #81: @20 = (@20/@21) */
  w20 /= w21;
  /* #82: (@12[8] = @20) */
  for (rr=w12+8, ss=(&w20); rr!=w12+9; rr+=1) *rr = *ss++;
  /* #83: @1 = @12' */
  for (i=0, rr=w1, cs=w12; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #84: @13 = mac(@1,@7,@13) */
  for (i=0, rr=w13; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #85: @4 = (@4+@13) */
  for (i=0, rr=w4, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #86: (@0[9:12] += @4) */
  for (rr=w0+9, ss=w4; rr!=w0+12; rr+=1) *rr += *ss++;
  /* #87: @22 = sin(@14) */
  w22 = sin( w14 );
  /* #88: @20 = (@20/@21) */
  w20 /= w21;
  /* #89: @1 = zeros(3x3) */
  casadi_clear(w1, 9);
  /* #90: @8 = @8' */
  /* #91: @1 = mac(@7,@8,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w8+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #92: @23 = @1[8] */
  for (rr=(&w23), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #93: @20 = (@20*@23) */
  w20 *= w23;
  /* #94: @22 = (@22*@20) */
  w22 *= w20;
  /* #95: @20 = sin(@14) */
  w20 = sin( w14 );
  /* #96: @18 = (@18/@19) */
  w18 /= w19;
  /* #97: @24 = 0 */
  w24 = 0.;
  /* #98: (@1[8] = @24) */
  for (rr=w1+8, ss=(&w24); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #99: @24 = @1[5] */
  for (rr=(&w24), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #100: @18 = (@18*@24) */
  w18 *= w24;
  /* #101: @20 = (@20*@18) */
  w20 *= w18;
  /* #102: @22 = (@22+@20) */
  w22 += w20;
  /* #103: @20 = 0 */
  w20 = 0.;
  /* #104: (@1[5] = @20) */
  for (rr=w1+5, ss=(&w20); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #105: @20 = 0 */
  w20 = 0.;
  /* #106: @12 = @1; (@12[7] = @20) */
  casadi_copy(w1, 9, w12);
  for (rr=w12+7, ss=(&w20); rr!=w12+8; rr+=1) *rr = *ss++;
  /* #107: @20 = 0 */
  w20 = 0.;
  /* #108: @9 = @12; (@9[4] = @20) */
  casadi_copy(w12, 9, w9);
  for (rr=w9+4, ss=(&w20); rr!=w9+5; rr+=1) *rr = *ss++;
  /* #109: @20 = @9[6] */
  for (rr=(&w20), ss=w9+6; ss!=w9+7; ss+=1) *rr++ = *ss;
  /* #110: @16 = (@16*@20) */
  w16 *= w20;
  /* #111: @18 = cos(@14) */
  w18 = cos( w14 );
  /* #112: @18 = sq(@18) */
  w18 = casadi_sq( w18 );
  /* #113: @16 = (@16/@18) */
  w16 /= w18;
  /* #114: @22 = (@22+@16) */
  w22 += w16;
  /* #115: @16 = 0 */
  w16 = 0.;
  /* #116: (@9[6] = @16) */
  for (rr=w9+6, ss=(&w16); rr!=w9+7; rr+=1) *rr = *ss++;
  /* #117: @16 = @9[3] */
  for (rr=(&w16), ss=w9+3; ss!=w9+4; ss+=1) *rr++ = *ss;
  /* #118: @11 = (@11*@16) */
  w11 *= w16;
  /* #119: @14 = cos(@14) */
  w14 = cos( w14 );
  /* #120: @14 = sq(@14) */
  w14 = casadi_sq( w14 );
  /* #121: @11 = (@11/@14) */
  w11 /= w14;
  /* #122: @22 = (@22+@11) */
  w22 += w11;
  /* #123: (@0[7] += @22) */
  for (rr=w0+7, ss=(&w22); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #124: @22 = cos(@10) */
  w22 = cos( w10 );
  /* #125: @24 = (@24/@19) */
  w24 /= w19;
  /* #126: @22 = (@22*@24) */
  w22 *= w24;
  /* #127: @24 = sin(@10) */
  w24 = sin( w10 );
  /* #128: @23 = (@23/@21) */
  w23 /= w21;
  /* #129: @24 = (@24*@23) */
  w24 *= w23;
  /* #130: @22 = (@22-@24) */
  w22 -= w24;
  /* #131: @24 = cos(@10) */
  w24 = cos( w10 );
  /* #132: @23 = @1[7] */
  for (rr=(&w23), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #133: @24 = (@24*@23) */
  w24 *= w23;
  /* #134: @22 = (@22-@24) */
  w22 -= w24;
  /* #135: @24 = sin(@10) */
  w24 = sin( w10 );
  /* #136: @23 = @12[4] */
  for (rr=(&w23), ss=w12+4; ss!=w12+5; ss+=1) *rr++ = *ss;
  /* #137: @24 = (@24*@23) */
  w24 *= w23;
  /* #138: @22 = (@22-@24) */
  w22 -= w24;
  /* #139: @24 = sin(@10) */
  w24 = sin( w10 );
  /* #140: @17 = (@17*@20) */
  w17 *= w20;
  /* #141: @24 = (@24*@17) */
  w24 *= w17;
  /* #142: @22 = (@22-@24) */
  w22 -= w24;
  /* #143: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #144: @15 = (@15*@16) */
  w15 *= w16;
  /* #145: @10 = (@10*@15) */
  w10 *= w15;
  /* #146: @22 = (@22+@10) */
  w22 += w10;
  /* #147: (@0[6] += @22) */
  for (rr=w0+6, ss=(&w22); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #148: @22 = @5[6] */
  for (rr=(&w22), ss=w5+6; ss!=w5+7; ss+=1) *rr++ = *ss;
  /* #149: @10 = cos(@22) */
  w10 = cos( w22 );
  /* #150: @15 = @5[7] */
  for (rr=(&w15), ss=w5+7; ss!=w5+8; ss+=1) *rr++ = *ss;
  /* #151: @16 = cos(@15) */
  w16 = cos( w15 );
  /* #152: @12 = zeros(3x3) */
  casadi_clear(w12, 9);
  /* #153: @24 = 0.104167 */
  w24 = 1.0416666666666667e-01;
  /* #154: @6 = (@24*@6) */
  for (i=0, rr=w6, cs=w6; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #155: @25 = input[2][0] */
  casadi_copy(arg[2], 6, w25);
  /* #156: @7 = @25[:3] */
  for (rr=w7, ss=w25+0; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #157: @7 = @7' */
  /* #158: @12 = mac(@6,@7,@12) */
  for (i=0, rr=w12; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w7+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #159: @24 = 0 */
  w24 = 0.;
  /* #160: @1 = @12; (@1[8] = @24) */
  casadi_copy(w12, 9, w1);
  for (rr=w1+8, ss=(&w24); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #161: @24 = @1[5] */
  for (rr=(&w24), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #162: @17 = (@16*@24) */
  w17  = (w16*w24);
  /* #163: @20 = @5[8] */
  for (rr=(&w20), ss=w5+8; ss!=w5+9; ss+=1) *rr++ = *ss;
  /* #164: @23 = cos(@20) */
  w23 = cos( w20 );
  /* #165: @21 = 0 */
  w21 = 0.;
  /* #166: (@1[5] = @21) */
  for (rr=w1+5, ss=(&w21); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #167: @21 = 0 */
  w21 = 0.;
  /* #168: @9 = @1; (@9[2] = @21) */
  casadi_copy(w1, 9, w9);
  for (rr=w9+2, ss=(&w21); rr!=w9+3; rr+=1) *rr = *ss++;
  /* #169: @21 = @9[7] */
  for (rr=(&w21), ss=w9+7; ss!=w9+8; ss+=1) *rr++ = *ss;
  /* #170: @19 = (@23*@21) */
  w19  = (w23*w21);
  /* #171: @17 = (@17-@19) */
  w17 -= w19;
  /* #172: @19 = sin(@20) */
  w19 = sin( w20 );
  /* #173: @11 = sin(@15) */
  w11 = sin( w15 );
  /* #174: @14 = (@19*@11) */
  w14  = (w19*w11);
  /* #175: @18 = 0 */
  w18 = 0.;
  /* #176: (@9[7] = @18) */
  for (rr=w9+7, ss=(&w18); rr!=w9+8; rr+=1) *rr = *ss++;
  /* #177: @18 = @9[4] */
  for (rr=(&w18), ss=w9+4; ss!=w9+5; ss+=1) *rr++ = *ss;
  /* #178: @26 = (@14*@18) */
  w26  = (w14*w18);
  /* #179: @17 = (@17+@26) */
  w17 += w26;
  /* #180: @26 = 0 */
  w26 = 0.;
  /* #181: (@9[4] = @26) */
  for (rr=w9+4, ss=(&w26); rr!=w9+5; rr+=1) *rr = *ss++;
  /* #182: @26 = 0 */
  w26 = 0.;
  /* #183: @27 = @9; (@27[1] = @26) */
  casadi_copy(w9, 9, w27);
  for (rr=w27+1, ss=(&w26); rr!=w27+2; rr+=1) *rr = *ss++;
  /* #184: @26 = @27[6] */
  for (rr=(&w26), ss=w27+6; ss!=w27+7; ss+=1) *rr++ = *ss;
  /* #185: @28 = (@19*@26) */
  w28  = (w19*w26);
  /* #186: @17 = (@17+@28) */
  w17 += w28;
  /* #187: @28 = (@23*@11) */
  w28  = (w23*w11);
  /* #188: @29 = 0 */
  w29 = 0.;
  /* #189: (@27[6] = @29) */
  for (rr=w27+6, ss=(&w29); rr!=w27+7; rr+=1) *rr = *ss++;
  /* #190: @29 = @27[3] */
  for (rr=(&w29), ss=w27+3; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #191: @30 = (@28*@29) */
  w30  = (w28*w29);
  /* #192: @17 = (@17+@30) */
  w17 += w30;
  /* #193: @10 = (@10*@17) */
  w10 *= w17;
  /* #194: @17 = sin(@22) */
  w17 = sin( w22 );
  /* #195: @30 = @12[8] */
  for (rr=(&w30), ss=w12+8; ss!=w12+9; ss+=1) *rr++ = *ss;
  /* #196: @31 = (@16*@30) */
  w31  = (w16*w30);
  /* #197: @32 = (@19*@11) */
  w32  = (w19*w11);
  /* #198: @33 = (@32*@21) */
  w33  = (w32*w21);
  /* #199: @31 = (@31+@33) */
  w31 += w33;
  /* #200: @33 = (@23*@18) */
  w33  = (w23*w18);
  /* #201: @31 = (@31+@33) */
  w31 += w33;
  /* #202: @33 = (@23*@11) */
  w33  = (w23*w11);
  /* #203: @34 = (@33*@26) */
  w34  = (w33*w26);
  /* #204: @31 = (@31+@34) */
  w31 += w34;
  /* #205: @34 = (@19*@29) */
  w34  = (w19*w29);
  /* #206: @31 = (@31-@34) */
  w31 -= w34;
  /* #207: @17 = (@17*@31) */
  w17 *= w31;
  /* #208: @10 = (@10-@17) */
  w10 -= w17;
  /* #209: (@0[6] += @10) */
  for (rr=w0+6, ss=(&w10); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #210: @10 = cos(@15) */
  w10 = cos( w15 );
  /* #211: @17 = cos(@22) */
  w17 = cos( w22 );
  /* #212: @31 = (@17*@21) */
  w31  = (w17*w21);
  /* #213: @34 = (@19*@31) */
  w34  = (w19*w31);
  /* #214: @35 = @1[2] */
  for (rr=(&w35), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #215: @34 = (@34-@35) */
  w34 -= w35;
  /* #216: @22 = sin(@22) */
  w22 = sin( w22 );
  /* #217: @35 = (@22*@18) */
  w35  = (w22*w18);
  /* #218: @36 = (@19*@35) */
  w36  = (w19*w35);
  /* #219: @34 = (@34+@36) */
  w34 += w36;
  /* #220: @36 = (@17*@26) */
  w36  = (w17*w26);
  /* #221: @37 = (@23*@36) */
  w37  = (w23*w36);
  /* #222: @34 = (@34+@37) */
  w34 += w37;
  /* #223: @37 = (@22*@29) */
  w37  = (w22*w29);
  /* #224: @38 = (@23*@37) */
  w38  = (w23*w37);
  /* #225: @34 = (@34+@38) */
  w34 += w38;
  /* #226: @10 = (@10*@34) */
  w10 *= w34;
  /* #227: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #228: @30 = (@17*@30) */
  w30  = (w17*w30);
  /* #229: @24 = (@22*@24) */
  w24  = (w22*w24);
  /* #230: @30 = (@30+@24) */
  w30 += w24;
  /* #231: @24 = @9[1] */
  for (rr=(&w24), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #232: @34 = (@19*@24) */
  w34  = (w19*w24);
  /* #233: @30 = (@30+@34) */
  w30 += w34;
  /* #234: @34 = 0 */
  w34 = 0.;
  /* #235: (@27[3] = @34) */
  for (rr=w27+3, ss=(&w34); rr!=w27+4; rr+=1) *rr = *ss++;
  /* #236: @34 = @27[0] */
  for (rr=(&w34), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #237: @38 = (@23*@34) */
  w38  = (w23*w34);
  /* #238: @30 = (@30+@38) */
  w30 += w38;
  /* #239: @15 = (@15*@30) */
  w15 *= w30;
  /* #240: @10 = (@10-@15) */
  w10 -= w15;
  /* #241: (@0[7] += @10) */
  for (rr=w0+7, ss=(&w10); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #242: @10 = cos(@20) */
  w10 = cos( w20 );
  /* #243: @31 = (@11*@31) */
  w31  = (w11*w31);
  /* #244: @35 = (@11*@35) */
  w35  = (w11*w35);
  /* #245: @31 = (@31+@35) */
  w31 += w35;
  /* #246: @24 = (@16*@24) */
  w24  = (w16*w24);
  /* #247: @31 = (@31+@24) */
  w31 += w24;
  /* #248: @26 = (@22*@26) */
  w26  = (w22*w26);
  /* #249: @31 = (@31+@26) */
  w31 += w26;
  /* #250: @29 = (@17*@29) */
  w29  = (w17*w29);
  /* #251: @31 = (@31-@29) */
  w31 -= w29;
  /* #252: @10 = (@10*@31) */
  w10 *= w31;
  /* #253: @20 = sin(@20) */
  w20 = sin( w20 );
  /* #254: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #255: @21 = (@22*@21) */
  w21  = (w22*w21);
  /* #256: @18 = (@18-@21) */
  w18 -= w21;
  /* #257: @36 = (@11*@36) */
  w36  = (w11*w36);
  /* #258: @18 = (@18+@36) */
  w18 += w36;
  /* #259: @37 = (@11*@37) */
  w37  = (w11*w37);
  /* #260: @18 = (@18+@37) */
  w18 += w37;
  /* #261: @34 = (@16*@34) */
  w34  = (w16*w34);
  /* #262: @18 = (@18+@34) */
  w18 += w34;
  /* #263: @20 = (@20*@18) */
  w20 *= w18;
  /* #264: @10 = (@10-@20) */
  w10 -= w20;
  /* #265: (@0[8] += @10) */
  for (rr=w0+8, ss=(&w10); rr!=w0+9; rr+=1) *rr += *ss++;
  /* #266: (@0[3:6] += @3) */
  for (rr=w0+3, ss=w3; rr!=w0+6; rr+=1) *rr += *ss++;
  /* #267: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  /* #268: @25 = zeros(6x1) */
  casadi_clear(w25, 6);
  /* #269: (@25[3:6] += @2) */
  for (rr=w25+3, ss=w2; rr!=w25+6; rr+=1) *rr += *ss++;
  /* #270: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #271: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #272: @10 = (@23*@16) */
  w10  = (w23*w16);
  /* #273: (@27[0] = @10) */
  for (rr=w27+0, ss=(&w10); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #274: @28 = (@28*@22) */
  w28 *= w22;
  /* #275: @10 = (@19*@17) */
  w10  = (w19*w17);
  /* #276: @28 = (@28-@10) */
  w28 -= w10;
  /* #277: (@27[3] = @28) */
  for (rr=w27+3, ss=(&w28); rr!=w27+4; rr+=1) *rr = *ss++;
  /* #278: @33 = (@33*@17) */
  w33 *= w17;
  /* #279: @28 = (@19*@22) */
  w28  = (w19*w22);
  /* #280: @33 = (@33+@28) */
  w33 += w28;
  /* #281: (@27[6] = @33) */
  for (rr=w27+6, ss=(&w33); rr!=w27+7; rr+=1) *rr = *ss++;
  /* #282: @19 = (@19*@16) */
  w19 *= w16;
  /* #283: (@27[1] = @19) */
  for (rr=w27+1, ss=(&w19); rr!=w27+2; rr+=1) *rr = *ss++;
  /* #284: @14 = (@14*@22) */
  w14 *= w22;
  /* #285: @19 = (@23*@17) */
  w19  = (w23*w17);
  /* #286: @14 = (@14+@19) */
  w14 += w19;
  /* #287: (@27[4] = @14) */
  for (rr=w27+4, ss=(&w14); rr!=w27+5; rr+=1) *rr = *ss++;
  /* #288: @32 = (@32*@17) */
  w32 *= w17;
  /* #289: @23 = (@23*@22) */
  w23 *= w22;
  /* #290: @32 = (@32-@23) */
  w32 -= w23;
  /* #291: (@27[7] = @32) */
  for (rr=w27+7, ss=(&w32); rr!=w27+8; rr+=1) *rr = *ss++;
  /* #292: @11 = (-@11) */
  w11 = (- w11 );
  /* #293: (@27[2] = @11) */
  for (rr=w27+2, ss=(&w11); rr!=w27+3; rr+=1) *rr = *ss++;
  /* #294: @22 = (@16*@22) */
  w22  = (w16*w22);
  /* #295: (@27[5] = @22) */
  for (rr=w27+5, ss=(&w22); rr!=w27+6; rr+=1) *rr = *ss++;
  /* #296: @16 = (@16*@17) */
  w16 *= w17;
  /* #297: (@27[8] = @16) */
  for (rr=w27+8, ss=(&w16); rr!=w27+9; rr+=1) *rr = *ss++;
  /* #298: @9 = @27' */
  for (i=0, rr=w9, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #299: @2 = mac(@9,@6,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #300: (@25[:3] += @2) */
  for (rr=w25+0, ss=w2; rr!=w25+3; rr+=1) *rr += *ss++;
  /* #301: output[0][1] = @25 */
  if (res[0]) casadi_copy(w25, 6, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void astrobee_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void astrobee_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void astrobee_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void astrobee_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int astrobee_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int astrobee_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real astrobee_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* astrobee_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* astrobee_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* astrobee_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* astrobee_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int astrobee_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 115;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
